In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
one_hot("amazing restaurant" ,50)#it gives a number between 1 and 30 ,  30 is the max limit

[15, 17]

In [4]:
vocab_size=50
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
encoded_reviews

[[35, 21],
 [15, 17],
 [6, 1],
 [12, 34, 30],
 [9, 19, 49],
 [9, 21],
 [48, 19, 2],
 [29, 39],
 [29, 38],
 [34, 1]]

In [5]:
#padding starts to equalise all statemnts

In [6]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
padded_reviews

array([[35, 21,  0],
       [15, 17,  0],
       [ 6,  1,  0],
       [12, 34, 30],
       [ 9, 19, 49],
       [ 9, 21,  0],
       [48, 19,  2],
       [29, 39,  0],
       [29, 38,  0],
       [34,  1,  0]])

In [7]:
embedded_vector_size=4

model=Sequential()
model.add(Embedding(vocab_size , embedded_vector_size , input_length=max_length , name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
X=padded_reviews
y=sentiment


In [9]:
model.compile(optimizer='adam' , loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 4)              200       
_________________________________________________________________
flatten (Flatten)            (None, 12)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 13        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(X,y,epochs=50,verbose=0)

In [11]:
loss,accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 363ms/step - loss: 0.6258 - accuracy: 1.0000


1.0

In [12]:
model.get_layer('embedding').get_weights()[0]

array([[ 0.03699536,  0.03803018,  0.04442824,  0.02342423],
       [ 0.01375315, -0.05218694, -0.03913816,  0.02873817],
       [ 0.04298624,  0.09336773,  0.02985806,  0.03772104],
       [ 0.00529671,  0.02635104, -0.00656886, -0.00744047],
       [ 0.0108852 ,  0.00226178, -0.00102573, -0.04879139],
       [-0.04051112, -0.01484763,  0.02632276, -0.03920506],
       [ 0.09225312,  0.0929146 ,  0.06811535, -0.01445159],
       [ 0.00899699, -0.03986025,  0.01024244, -0.00784419],
       [ 0.02999203, -0.02800391,  0.0049663 , -0.00359771],
       [-0.05986139, -0.01321665, -0.04739831,  0.00728079],
       [-0.01536723,  0.03503558, -0.0002959 , -0.00180782],
       [-0.03486741, -0.02956721,  0.02276433, -0.04599511],
       [ 0.00098042,  0.06326135,  0.0493856 , -0.08015639],
       [ 0.04931302, -0.01558537,  0.04027894, -0.03391226],
       [-0.02034395, -0.00383887, -0.03021753,  0.04523119],
       [ 0.0502929 ,  0.05039904,  0.01514604, -0.01873624],
       [ 0.01720972,  0.

In [13]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [14]:
weights[6]

array([ 0.09225312,  0.0929146 ,  0.06811535, -0.01445159], dtype=float32)

In [15]:
weights[34]

array([-0.03136429, -0.09556521, -0.08915755,  0.03833654], dtype=float32)

In [16]:
weights[3]

array([ 0.00529671,  0.02635104, -0.00656886, -0.00744047], dtype=float32)