In [1]:
import numpy as np

y_predicted=np.array([1,1,0,0,1])
y_true=np.array([0.3,0.7,1,0,0.5])

In [2]:
#mean absolute error

In [9]:
def mae(y_true,y_predicted):
    total_error=0
    for yt, yp in zip(y_true,y_predicted):
        total_error+= abs(yt-yp)
    print("total error: ", total_error)
    
    mae = total_error/len(y_true)
    print("MAE: ",mae)
    return mae

In [10]:
mae(y_true,y_predicted)

total error:  2.5
MAE:  0.5


0.5

In [ ]:
#same function using numpy

In [12]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [13]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [14]:
np.sum(np.abs(y_predicted-y_true))

2.5

In [15]:
#log loss or binary_cross_entropy

In [16]:
epsilon=1e-15

In [17]:
y_predicted_new=[max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [18]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [19]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [20]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [21]:
def log_loss(y_true,y_predicted):
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [22]:
log_loss(y_true,y_predicted)

17.2696280766844