In [1]:
import numpy as np

In [2]:
revenue=np.array([[180,200,120],[24,36,40],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [4]:
profit=revenue-expenses
profit

array([[100, 110,  20],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [5]:
price_per_unit=np.array([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])

In [7]:
price_per_unit*units#this is actually wrong we expected a dot product here

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [8]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [ ]:
#exercise

In [9]:
revenue_in_million=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
usd=np.array([75])

In [10]:
indian_rupee=revenue_in_million*usd
indian_rupee

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [ ]:
#exercise 2

In [14]:
units=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_perunit=np.array([20,30,15])

In [15]:
total_sales=np.dot(price_perunit,units)
total_sales

array([1900, 2640, 1430])